### ISSUE TITLE
numResults, numYears configuration for iNat APIs appear to be ignored 

### ISSUE THREAD

**Issue by amb26** [IMERSS/inat-components#10]
`numResults` as seen in https://github.com/IMERSS/inat-components/blob/main/apps/standalone/src/inat.config.json#L21 appears to be ignored in favour of the constant `PER_PAGE` written in constants.ts https://github.com/IMERSS/inat-components/blob/main/shared/constants.ts#L2

It appears that numYears is also ignored in favour of the code constant 10 - https://github.com/IMERSS/inat-components/blob/main/packages/inat-components/src/components/year-dropdown/year-dropdown.tsx#L15

**Comment by benkeen** [comment]
Closing, but not actually verified yet so expect _explosions_! Just re-familiarizing myself with this app. Will check it all works shortly.
