### ISSUE TITLE
Absence of stable selector for general-module-panel

### ISSUE THREAD

**Issue by amb26** [IMERSS/inat-components#8]
For the Howe Sound integration I needed to restyle the general module panel to be fixed-sized with a scrollbar overflow, but since it didn't have a stable classname of its own I had to use a "flying blind" selector as so:

````
#inat-components > div > div:last-child {
....
````
https://github.com/IMERSS/howe-sound-mapping/blob/main/src/css/howe.css#L96

Most straightforwardly this could be resolved by simply issuing a stable classname like the one emitted for `inat-tabs` but I notice that there are already plenty of classnames for internal use of the form `general-module_panel__WjWzy` - I understand the intent here is precisely to stop markup being hit "collaterally" by selectors not written by the original author as part of their build process, but I wonder whether the most economical thing in the long run might be to disable the name mangling which makes them unstable?

**Comment by benkeen** [comment]
Sure, np. I'll add some more classes to the `classes` prop for the TaxonPanel component, namely:

```jsx
<TaxonPanel
  ... 
  classes={{
    ... 
    recentObservationsPanel: '...', 
    commonTaxaPanel: '...',
    favouritesPanel: '...',
    statsPanel: '...',
  }}
/>
```

These'll be appended to the same DOM element you mentioned so consumers can add their own styling - that's the purpose of the `classes` prop. The existing classes with the random suffix are fine - they're for internal styling purposes only.
